spring:
  application:
    name: ecommerce-pricing-api
  messages:
    basename: i18n/ValidationMessages
  datasource:
    url: jdbc:h2:mem:pricingdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  h2:
    console:
      enabled: true

server:
  port: 8090

api:
  base-url: http://localhost:${server.port}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
